### PR TITLE
fix: add more TUI sanity for interactive flows

### LINKED ISSUE #37: Task list is a random order
The task list is in a random order and changes on each run of `eirctl`.

It'd be nice to have a consistent, sorted list.

### PR DESCRIPTION
**Pull request by dnitsch**
closes #37  and #38 

ordering of pipelines alphabetically and then tasks + pagination based on windows size
image

filter functionality
image

### CODE REVIEW

File: internal/cmdutils/cmdutils.go [hunk 1]
```diff
@@ -21,29 +22,38 @@ const (
...
 	if !showPipelineOnly {
-		for _, task := range conf.Tasks {
-			optionMap = append(optionMap, huh.NewOption(fmt.Sprintf("%s - %s", task.Name, fmt.Sprintf(GREY_TERMINAL, task.Description)), task.Name))
+		tasks := utils.MapKeys(conf.Tasks)
+		slices.Sort(tasks)
+		for _, tsk := range tasks {
+			task := conf.Tasks[tsk]
+			desc := task.Description
+			if desc == "" {
+				desc = "No description"
```
Comment (ElvenSpellmaker) [inline internal/cmdutils/cmdutils.go:49]: Possibly something like `TODO: No description` or `**MISSING DESCRIPTION**`?

**Review by ElvenSpellmaker — APPROVED** [review]
NICE one, it also fixes the other bug of not being able to select the task name too!
